### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by SAWRJJ** [Owen718/FiveAPlus-Network#1]
Thank you very much for the excellent model you provided. At present, I want to train my own data set to see the results. How should I set up config to start training?

**Comment by Owen718** [comment]
Hi, thank you very much for your interest in our work. As our work has not yet been accepted by any conference or journal, we have not released the training code at this time. However, you can refer to the training settings in our paper and model code presented for training purposes. Thank you.

**Comment by Owen718** [comment]
Finished.

**Comment by Owen718** [comment]
We have already made our training code available! Enjoy!

**Comment by Owen718** [comment]
> Thank you very much for the excellent model you provided. At present, I want to train my own data set to see the results. How should I set up config to start training?

We have already made our training code available! Enjoy!
