### ISSUE TITLE
inference effect 

### ISSUE THREAD

**Issue by lewis081** [Owen718/FiveAPlus-Network#2]
Dear author,
　It's an amazing and impressive work on speed, experimental results and visual effect in your arxiv paper.  
　But I wonder why i can not obtain the your paper's  avg PSNR, SSIM  and good visual effect when i used your two pre-trained models to inference. Could you help to explain the reasons?
![image](https://github.com/Owen718/FiveAPlus-Network/assets/5345837/66882b47-3070-45b8-ae05-84de51c3b2d5)
![image](https://github.com/Owen718/FiveAPlus-Network/assets/5345837/2b0a9833-3657-41c1-a155-4e3f04a35986)

**Comment by Owen718** [comment]
Hello, may I ask what are the specific values of PSNR and SSIM of the T90 test results on your end?
Based on the visual result you provided, I am unable to discern what occurred.

**Comment by Owen718** [comment]
Please do not hesitate to reach out to me. My WeChatID wxh59309063.

**Comment by Owen718** [comment]
Solved.
