### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by lcaldsdhr** [Owen718/FiveAPlus-Network#3]
hello !

i want to know when will the training code be released?

**Comment by Owen718** [comment]
Hello, thank you for your interest in our work. The paper has not been accepted by any conference yet and is currently under review. Once the paper is accepted, we will release the complete training code. Please note that we have already open-sourced the pre-trained weights. You may use your own training code to train our network.

**Comment by lcaldsdhr** [comment]
ok ， thanks for your reply

**Comment by Owen718** [comment]
We have already made our training code available! Enjoy!

**Comment by Owen718** [comment]
Solved.
